#!/bin/sh
# chkconfig: 2345 80 30
# description: JBoss auto start-stop script.

# Source function library.
#. /etc/rc.d/init.d/functions

# Get config.
#. /etc/sysconfig/network

# Check that networking is up.
#[ "${NETWORKING}" = "no" ] && exit 0

### CHANGE THE STARTUP PATH TO YOUR START SCRIPT ###

JBOSS_HOME='/home/jboss-5.1.0.GA'

shutdown=$(killall java)

#shutdown=$(/home/jboss-5.1.0.GA/bin/shutdown.sh)


start(){

#JBOSS_STATUS=$(ps -ef | grep -i jboss | grep -v grep)

JBOSS_STATUS=$(ps -ef | grep -i java | grep jboss-5 | awk -F " " '{print $2}')

JBOSS_HOME=/home/jboss-5.1.0.GA



if [[ $JBOSS_STATUS ]]

then

echo "Jboss is Already Running with PID: $JBOSS_STATUS"

else

echo -n $"Jboss is Starting >> Stay Calm : "
echo
#cd $JBOSS_HOME/bin

#./run.sh -c all -b 0.0.0.0 -Djboss.service.binding.set=ports-default > /dev/null 2> /dev/null &

#su jboss -c "$JBOSS_HOME/bin/run.sh -c default -b 0.0.0.0 > /dev/null 2> /dev/null & $@"
sudo -H -u jboss $JBOSS_HOME/bin/run.sh -c default -b 0.0.0.0 > /dev/null 2> /dev/null &
#echo $?

#cd $JBOSS_HOME/bin

#./run.sh -c default -b 0.0.0.0 -Djboss.service.binding.set=ports-01 > /dev/null 2> /dev/null &

#$JBOSS_HOME/bin/run.sh -c default -b 0.0.0.0 -Djboss.service.binding.set=ports-01 > /dev/null 2> /dev/null &

#echo $?

sleep 3m 

#result1=$(tail -5 /home/jboss-5.1.0.GA/server/all/log/server.log | grep -i "started in" --color)

result=$(tail -5 /home/jboss-5.1.0.GA/server/default/log/server.log | grep -i "started in" --color)

if [[ $result ]]
then
echo "$result"
echo
else
echo "Jboss is Not Started "
fi
echo
fi
}

stop(){

#action $"Stopping JBoss service: " #$shutdown
echo "Stopping Jboss Service:" 
echo
$shutdown

#defunct=$(ps -ef | grep [d]efunct | awk '{print $3}' | sort | uniq | egrep -v '^1$')

#if [[ $defunct ]]
#then
#kill -9 $defunct
#fi

sleep 3
RETVAL=$?
echo
}

log(){

tail -40f /home/jboss-5.1.0.GA/server/default/log/server.log

echo

}


restart(){
stop
sleep 30
start
}


status(){

sleep 5
JBOSS_STATUS=$(ps -ef | grep -i java | grep jboss| grep -v grep | awk -F " " '{print $2}')
if [[ $JBOSS_STATUS ]]
then
echo "Jboss is Running with PID: "$JBOSS_STATUS
echo
else
echo "Jboss is Not Running"
echo
fi
}
# See how we were called.
case "$1" in
start)
start
;;
stop)
stop
;;
restart)
restart
;;
status)
status
;;
log)
log
;;
*)
echo $"Usage: $0 {start|stop|restart}"
exit 1
esac

